// Mock Data for Development
import { Customer, CustomerDetail, DashboardStats, DiscountRule, PointsRule, SMSCampaign, QuickBooksOrder, DiscountCode, ContactList } from '@/types';

// Helper to generate dates
const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

// Mock Customers
export const mockCustomers: Customer[] = [
    {
        id: '1',
        name: 'John Smith',
        email: 'john.smith@email.com',
        phone: '(555) 123-4567',
        type: 'GC',
        points: 2500,
        discountRate: 15,
        customDiscountCode: 'JOHNGC15',
        customDiscountRate: 5,
        createdAt: daysAgo(120),
        updatedAt: daysAgo(5),
    },
    {
        id: '2',
        name: 'Sarah Johnson',
        email: 'sarah.j@design.co',
        phone: '(555) 234-5678',
        type: 'DESIGNER',
        points: 4800,
        discountRate: 20,
        customDiscountCode: 'SARAHVIP',
        customDiscountRate: 10,
        createdAt: daysAgo(90),
        updatedAt: daysAgo(2),
    },
    {
        id: '3',
        name: 'Michael Chen',
        email: 'mchen@homemail.com',
        phone: '(555) 345-6789',
        type: 'REGULAR',
        points: 350,
        discountRate: 5,
        createdAt: daysAgo(60),
        updatedAt: daysAgo(10),
    },
    {
        id: '4',
        name: 'Emily Davis',
        email: 'emily.d@builders.net',
        phone: '(555) 456-7890',
        type: 'WHOLESALE',
        points: 8200,
        discountRate: 25,
        customDiscountCode: 'DAVISWHOLE',
        customDiscountRate: 8,
        createdAt: daysAgo(180),
        updatedAt: daysAgo(1),
    },
    {
        id: '5',
        name: 'Robert Wilson',
        email: 'rwilson@interior.com',
        phone: '(555) 567-8901',
        type: 'DESIGNER',
        points: 1200,
        discountRate: 20,
        createdAt: daysAgo(45),
        updatedAt: daysAgo(7),
    },
    {
        id: '6',
        name: 'Lisa Anderson',
        email: 'lisa.a@email.com',
        phone: '(555) 678-9012',
        type: 'REGULAR',
        points: 0,
        discountRate: 0,
        createdAt: daysAgo(15),
        updatedAt: daysAgo(15),
    },
    {
        id: '7',
        name: 'David Martinez',
        email: 'dmartinez@construct.co',
        phone: '(555) 789-0123',
        type: 'WHOLESALE',
        points: 5600,
        discountRate: 25,
        createdAt: daysAgo(200),
        updatedAt: daysAgo(3),
    },
    {
        id: '8',
        name: 'Jennifer Brown',
        email: 'jbrown@designstudio.com',
        phone: '(555) 890-1234',
        type: 'DESIGNER',
        points: 3100,
        discountRate: 20,
        createdAt: daysAgo(75),
        updatedAt: daysAgo(4),
    },
];

// Mock Orders
export const mockOrders: QuickBooksOrder[] = [
    {
        id: 'ord-001',
        qbId: 'QB-INV-001',
        qbInvoiceId: 'INV-2024-001',
        customerName: 'John Smith',
        customerId: '1',
        total: 2450.00,
        amount: 2450.00,
        status: 'COMPLETED',
        syncStatus: 'SYNCED',
        createdAt: daysAgo(2),
        discountCode: 'JOHNGC15',
    },
    {
        id: 'ord-002',
        qbId: 'QB-INV-002',
        qbInvoiceId: 'INV-2024-002',
        customerName: 'Sarah Johnson',
        customerId: '2',
        total: 5800.00,
        amount: 5800.00,
        status: 'COMPLETED',
        syncStatus: 'SYNCED',
        createdAt: daysAgo(5),
        discountCode: 'SARAHVIP',
    },
    {
        id: 'ord-003',
        qbId: 'QB-INV-003',
        qbInvoiceId: 'INV-2024-003',
        customerName: 'Michael Chen',
        customerId: '3',
        total: 890.00,
        amount: 890.00,
        status: 'PENDING',
        syncStatus: 'PENDING',
        createdAt: daysAgo(1),
    },
    {
        id: 'ord-004',
        qbId: 'QB-INV-004',
        qbInvoiceId: 'INV-2024-004',
        customerName: 'Emily Davis',
        customerId: '4',
        total: 12500.00,
        amount: 12500.00,
        status: 'COMPLETED',
        syncStatus: 'SYNCED',
        createdAt: daysAgo(7),
        discountCode: 'HOLIDAY2024',
    },
    {
        id: 'ord-005',
        qbId: 'QB-INV-005',
        qbInvoiceId: 'INV-2024-005',
        customerName: 'Robert Wilson',
        customerId: '5',
        total: 3200.00,
        amount: 3200.00,
        status: 'CANCELLED',
        syncStatus: 'SYNCED',
        createdAt: daysAgo(10),
    },
    // Referral Orders - Orders placed by others using someone's discount code
    {
        id: 'ord-006',
        qbId: 'QB-INV-006',
        qbInvoiceId: 'INV-2024-006',
        customerName: 'Lisa Anderson',
        customerId: '6',
        total: 1850.00,
        amount: 1850.00,
        status: 'COMPLETED',
        syncStatus: 'SYNCED',
        createdAt: daysAgo(3),
        discountCode: 'JOHNGC15',
        codeOwnerId: '1',
        codeOwnerName: 'John Smith',
    },
    {
        id: 'ord-007',
        qbId: 'QB-INV-007',
        qbInvoiceId: 'INV-2024-007',
        customerName: 'David Martinez',
        customerId: '7',
        total: 4200.00,
        amount: 4200.00,
        status: 'COMPLETED',
        syncStatus: 'SYNCED',
        createdAt: daysAgo(8),
        discountCode: 'SARAHVIP',
        codeOwnerId: '2',
        codeOwnerName: 'Sarah Johnson',
    },
    {
        id: 'ord-008',
        qbId: 'QB-INV-008',
        qbInvoiceId: 'INV-2024-008',
        customerName: 'Jennifer Brown',
        customerId: '8',
        total: 2100.00,
        amount: 2100.00,
        status: 'COMPLETED',
        syncStatus: 'SYNCED',
        createdAt: daysAgo(4),
        discountCode: 'JOHNGC15',
        codeOwnerId: '1',
        codeOwnerName: 'John Smith',
    },
];

// Mock Customer Detail
export const mockCustomerDetail: CustomerDetail = {
    ...mockCustomers[0],
    orders: [
        {
            id: 'ord-001',
            customerId: '1',
            total: 2450.00,
            status: 'COMPLETED',
            createdAt: daysAgo(2),
            items: [
                { id: 'item-1', name: 'Hardwood Flooring - Oak', quantity: 500, price: 4.50 },
                { id: 'item-2', name: 'Installation Service', quantity: 1, price: 200 },
            ],
        },
        {
            id: 'ord-006',
            customerId: '1',
            total: 1850.00,
            status: 'COMPLETED',
            createdAt: daysAgo(30),
            items: [
                { id: 'item-3', name: 'Vinyl Plank Flooring', quantity: 400, price: 3.50 },
                { id: 'item-4', name: 'Underlayment', quantity: 400, price: 1.10 },
            ],
        },
    ],
    pointsHistory: [
        { id: 'pts-1', customerId: '1', amount: 245, type: 'EARN', description: 'Order #ord-001', createdAt: daysAgo(2) },
        { id: 'pts-2', customerId: '1', amount: 185, type: 'EARN', description: 'Order #ord-006', createdAt: daysAgo(30) },
        { id: 'pts-3', customerId: '1', amount: -100, type: 'REDEEM', description: 'Points redemption', createdAt: daysAgo(15) },
    ],
    notes: 'Preferred customer. Specializes in commercial projects.',
};

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
    totalRevenue: 156780,
    revenueChange: 12.5,
    activeCustomers: 248,
    customersChange: 8.2,
    totalOrders: 1642,
    ordersChange: 15.3,
    pendingOrders: 23,
    pendingChange: -5.1,
    recentOrders: mockOrders.slice(0, 5),
    topCustomers: [
        { id: '4', name: 'Emily Davis', totalSpent: 45600, orderCount: 12 },
        { id: '2', name: 'Sarah Johnson', totalSpent: 32400, orderCount: 8 },
        { id: '1', name: 'John Smith', totalSpent: 28900, orderCount: 15 },
        { id: '7', name: 'David Martinez', totalSpent: 21500, orderCount: 6 },
        { id: '8', name: 'Jennifer Brown', totalSpent: 18200, orderCount: 5 },
    ],
};

// Mock Discount Rules
export const mockDiscountRules: DiscountRule[] = [
    {
        id: 'rule-001',
        name: 'GC Standard Discount',
        description: 'Standard 15% discount for General Contractors',
        type: 'PERCENTAGE',
        value: 15,
        customerTypes: ['GC'],
        isActive: true,
        usageCount: 342,
        createdAt: daysAgo(365),
        updatedAt: daysAgo(30),
    },
    {
        id: 'rule-002',
        name: 'Designer Discount',
        description: '20% discount for Interior Designers',
        type: 'PERCENTAGE',
        value: 20,
        customerTypes: ['DESIGNER'],
        isActive: true,
        usageCount: 189,
        createdAt: daysAgo(365),
        updatedAt: daysAgo(30),
    },
];

// Mock Points Rules
export const mockPointsRules: PointsRule[] = [
    {
        id: 'points-001',
        name: 'Standard Earning',
        description: 'Earn 1 point per $1 spent',
        earnRate: 1,
        redemptionRate: 0.01,
        customerTypes: ['GC', 'DESIGNER'],
        minPointsToRedeem: 100,
        isActive: true,
        createdAt: daysAgo(365),
        updatedAt: daysAgo(60),
    },
];

// Mock SMS Campaigns
export const mockSMSCampaigns: SMSCampaign[] = [
    {
        id: 'sms-001',
        name: 'Winter Sale Announcement',
        message: '❄️ Winter Sale! Get 25% off all hardwood flooring this week only. Use code WINTER25 at checkout.',
        status: 'SENT',
        recipientFilter: 'ALL',
        recipientCount: 248,
        sentCount: 245,
        sentAt: daysAgo(7),
        createdAt: daysAgo(10),
        updatedAt: daysAgo(7),
    },
    {
        id: 'sms-002',
        name: 'VIP Early Access',
        message: '⭐ VIP Early Access: New luxury vinyl collection arriving next week. Preview exclusive discount inside!',
        status: 'SCHEDULED',
        recipientFilter: 'GC',
        recipientCount: 82,
        scheduledAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
        createdAt: daysAgo(2),
        updatedAt: daysAgo(2),
    },
    {
        id: 'sms-003',
        name: 'Designer Workshop Invite',
        message: '🎨 Exclusive: Free design workshop next Saturday. Limited spots - RSVP today!',
        status: 'DRAFT',
        recipientFilter: 'DESIGNER',
        recipientCount: 45,
        createdAt: daysAgo(1),
        updatedAt: daysAgo(1),
    },
    {
        id: 'sms-004',
        name: 'Holiday Hours Notice',
        message: '🎄 Holiday Hours: We will be closed Dec 24-26. Orders placed now ship before Christmas!',
        status: 'SENT',
        recipientFilter: 'ALL',
        recipientCount: 248,
        sentCount: 248,
        sentAt: daysAgo(30),
        createdAt: daysAgo(35),
        updatedAt: daysAgo(30),
    },
];

// Mock SMS Templates
export const mockSMSTemplates = [
    { id: 'tpl-001', name: 'Sale Announcement', content: '🎉 Sale Alert! [DISCOUNT]% off [PRODUCT]. Use code [CODE] at checkout. Valid until [DATE].', createdAt: daysAgo(100) },
    { id: 'tpl-002', name: 'Order Confirmation', content: 'Thank you for your order #[ORDER_ID]! Your total is $[AMOUNT]. We\'ll notify you when it ships.', createdAt: daysAgo(100) },
    { id: 'tpl-003', name: 'Appointment Reminder', content: 'Reminder: Your appointment is scheduled for [DATE] at [TIME]. Reply YES to confirm.', createdAt: daysAgo(100) },
];

// Mock Discount Codes
export const mockDiscountCodes: DiscountCode[] = [
    // Generic Codes (Promo Codes)
    {
        id: 'code-001',
        code: 'HOLIDAY2024',
        type: 'GENERIC',
        description: 'Holiday Season Special',
        discountPercent: 20,
        isActive: true,
        usageCount: 5,
        uniqueUsersCount: 4,
        createdAt: daysAgo(30),
        expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
        usageHistory: [
            { id: 'usage-001', customerId: '1', customerName: 'John Smith', customerType: 'GC', orderId: 'ord-101', orderTotal: 1200, discountAmount: 240, usedAt: daysAgo(5) },
            { id: 'usage-002', customerId: '2', customerName: 'Sarah Johnson', customerType: 'DESIGNER', orderId: 'ord-102', orderTotal: 2500, discountAmount: 500, usedAt: daysAgo(8) },
            { id: 'usage-003', customerId: '3', customerName: 'Michael Chen', customerType: 'REGULAR', orderId: 'ord-103', orderTotal: 800, discountAmount: 160, usedAt: daysAgo(12) },
            { id: 'usage-004', customerId: '4', customerName: 'Emily Davis', customerType: 'WHOLESALE', orderId: 'ord-104', orderTotal: 5000, discountAmount: 1000, usedAt: daysAgo(15) },
            { id: 'usage-005', customerId: '1', customerName: 'John Smith', customerType: 'GC', orderId: 'ord-105', orderTotal: 900, discountAmount: 180, usedAt: daysAgo(20) },
        ],
    },
    {
        id: 'code-002',
        code: 'WELCOME10',
        type: 'GENERIC',
        description: 'New Customer Welcome Code',
        discountPercent: 10,
        isActive: true,
        usageCount: 3,
        uniqueUsersCount: 3,
        createdAt: daysAgo(365),
        usageHistory: [
            { id: 'usage-006', customerId: '6', customerName: 'Lisa Anderson', customerType: 'REGULAR', orderId: 'ord-106', orderTotal: 450, discountAmount: 45, usedAt: daysAgo(10) },
            { id: 'usage-007', customerId: '3', customerName: 'Michael Chen', customerType: 'REGULAR', orderId: 'ord-107', orderTotal: 680, discountAmount: 68, usedAt: daysAgo(45) },
            { id: 'usage-008', customerId: '5', customerName: 'Robert Wilson', customerType: 'DESIGNER', orderId: 'ord-108', orderTotal: 1200, discountAmount: 120, usedAt: daysAgo(60) },
        ],
    },
    {
        id: 'code-006',
        code: 'SUMMER25',
        type: 'GENERIC',
        description: 'Summer Sale Promotion',
        discountPercent: 25,
        isActive: true,
        usageCount: 0,
        uniqueUsersCount: 0,
        createdAt: daysAgo(7),
        expiresAt: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
        usageHistory: [],
    },
    // Exclusive Codes (Customer-specific codes)
    {
        id: 'code-003',
        code: 'JOHNGC15',
        type: 'EXCLUSIVE',
        description: 'Exclusive code for John Smith',
        discountPercent: 5,
        isActive: true,
        usageCount: 3,
        uniqueUsersCount: 1,
        assignedTo: {
            customerId: '1',
            customerName: 'John Smith',
            customerType: 'GC',
        },
        createdAt: daysAgo(120),
        usageHistory: [
            { id: 'usage-009', customerId: '1', customerName: 'John Smith', customerType: 'GC', orderId: 'ord-109', orderTotal: 3500, discountAmount: 175, usedAt: daysAgo(3) },
            { id: 'usage-010', customerId: '1', customerName: 'John Smith', customerType: 'GC', orderId: 'ord-110', orderTotal: 2200, discountAmount: 110, usedAt: daysAgo(25) },
            { id: 'usage-011', customerId: '1', customerName: 'John Smith', customerType: 'GC', orderId: 'ord-111', orderTotal: 1800, discountAmount: 90, usedAt: daysAgo(50) },
        ],
    },
    {
        id: 'code-004',
        code: 'SARAHVIP',
        type: 'EXCLUSIVE',
        description: 'Exclusive code for Sarah Johnson',
        discountPercent: 10,
        isActive: true,
        usageCount: 5,
        uniqueUsersCount: 1,
        assignedTo: {
            customerId: '2',
            customerName: 'Sarah Johnson',
            customerType: 'DESIGNER',
        },
        createdAt: daysAgo(90),
        usageHistory: [
            { id: 'usage-012', customerId: '2', customerName: 'Sarah Johnson', customerType: 'DESIGNER', orderId: 'ord-112', orderTotal: 4200, discountAmount: 420, usedAt: daysAgo(2) },
            { id: 'usage-013', customerId: '2', customerName: 'Sarah Johnson', customerType: 'DESIGNER', orderId: 'ord-113', orderTotal: 1800, discountAmount: 180, usedAt: daysAgo(15) },
            { id: 'usage-014', customerId: '2', customerName: 'Sarah Johnson', customerType: 'DESIGNER', orderId: 'ord-114', orderTotal: 3100, discountAmount: 310, usedAt: daysAgo(30) },
            { id: 'usage-015', customerId: '2', customerName: 'Sarah Johnson', customerType: 'DESIGNER', orderId: 'ord-115', orderTotal: 2500, discountAmount: 250, usedAt: daysAgo(45) },
            { id: 'usage-016', customerId: '2', customerName: 'Sarah Johnson', customerType: 'DESIGNER', orderId: 'ord-116', orderTotal: 1650, discountAmount: 165, usedAt: daysAgo(60) },
        ],
    },
    {
        id: 'code-005',
        code: 'DAVISWHOLE',
        type: 'EXCLUSIVE',
        description: 'Exclusive code for Emily Davis',
        discountPercent: 8,
        isActive: true,
        usageCount: 2,
        uniqueUsersCount: 1,
        assignedTo: {
            customerId: '4',
            customerName: 'Emily Davis',
            customerType: 'WHOLESALE',
        },
        createdAt: daysAgo(180),
        usageHistory: [
            { id: 'usage-017', customerId: '4', customerName: 'Emily Davis', customerType: 'WHOLESALE', orderId: 'ord-117', orderTotal: 8500, discountAmount: 680, usedAt: daysAgo(7) },
            { id: 'usage-018', customerId: '4', customerName: 'Emily Davis', customerType: 'WHOLESALE', orderId: 'ord-118', orderTotal: 12000, discountAmount: 960, usedAt: daysAgo(35) },
        ],
    },
    {
        id: 'code-007',
        code: 'MARTINEZVIP',
        type: 'EXCLUSIVE',
        description: 'Exclusive code for David Martinez',
        discountPercent: 12,
        isActive: true,
        usageCount: 1,
        uniqueUsersCount: 1,
        assignedTo: {
            customerId: '7',
            customerName: 'David Martinez',
            customerType: 'WHOLESALE',
        },
        createdAt: daysAgo(60),
        usageHistory: [
            { id: 'usage-019', customerId: '7', customerName: 'David Martinez', customerType: 'WHOLESALE', orderId: 'ord-119', orderTotal: 6200, discountAmount: 744, usedAt: daysAgo(10) },
        ],
    },
    {
        id: 'code-008',
        code: 'JENDESIGN',
        type: 'EXCLUSIVE',
        description: 'Exclusive code for Jennifer Brown',
        discountPercent: 8,
        isActive: true,
        usageCount: 0,
        uniqueUsersCount: 0,
        assignedTo: {
            customerId: '8',
            customerName: 'Jennifer Brown',
            customerType: 'DESIGNER',
        },
        createdAt: daysAgo(30),
        usageHistory: [],
    },
];

// Mock Users
export const mockUsers: import('@/types').User[] = [
    {
        id: 'user-001',
        name: 'Admin User',
        email: 'admin@example.com',
        role: 'ADMIN',
        status: 'ACTIVE',
        createdAt: daysAgo(365),
    },
    {
        id: 'user-002',
        name: 'Staff Member',
        email: 'staff@example.com',
        role: 'STAFF',
        status: 'ACTIVE',
        createdAt: daysAgo(180),
    },
    {
        id: 'user-003',
        name: 'John Doe',
        email: 'john@example.com',
        role: 'STAFF',
        status: 'INACTIVE',
        createdAt: daysAgo(30),
    },
];

// Mock Settings
export const mockSettings = {
    discountRates: {
        GC: 25,
        DESIGNER: 25,
        WHOLESALE: 25,
    },
    pointsConfig: {
        earnRate: 1, // 1 point per dollar
        pointsPerDollar: 100, // 100 points = $1
        minRedeemPoints: 100, // minimum 100 points to redeem
    },
};

// Mock Contact Lists
export const mockContactLists: ContactList[] = [
    {
        id: 'list-001',
        name: 'Fall Conference Leads',
        description: 'Leads collected from the Home & Garden Show',
        count: 142,
        source: 'EXCEL_IMPORT',
        createdAt: daysAgo(50),
        updatedAt: daysAgo(50),
    },
    {
        id: 'list-002',
        name: 'VIP Local Designers',
        description: 'Top tier designers in the downtown area',
        count: 56,
        source: 'MANUAL',
        createdAt: daysAgo(20),
        updatedAt: daysAgo(15),
    },
    {
        id: 'list-003',
        name: 'Previous Year Large Orders',
        description: 'Customers with orders > $5k in 2023',
        count: 89,
        source: 'SYSTEM',
        createdAt: daysAgo(5),
        updatedAt: daysAgo(5),
    },
];
